### PR TITLE
🐛 properly handle insecure flag for host scans

### LINKED ISSUE #3995: http resource does not respect insecure connection flag
**Describe the bug**

```
cnspec shell host https://wordpress.lndo.site --insecure true
→ loaded configuration from /Users/atomic111/.config/mondoo/mondoo.yml using source default
→ connected to Network Host
  ___ _ __  ___ _ __   ___  ___
 / __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__
 \___|_| |_|___/ .__/ \___|\___|
   mondoo™     |_|
cnspec> http.get
1 error occurred:
 * Get "https://wordpress.insecure.site:443": tls: failed to verify certificate: x509: “wordpress” certificate is not trusted
http.get: http.get url=url id = https://wordpress.insecure.site:443 statusCode=null
cnspec>

```

**To Reproduce**

1. Connect to an a self-signed certificate
2. use http.get resource

**Expected behavior**

http resource respects the `insecure` flag

**Additional context**

We parse the flag here https://github.com/mondoohq/cnquery/blob/main/providers/network/provider/provider.go#L42-L45. We need a custom http client https://github.com/mondoohq/cnquery/blob/main/providers/network/resources/http.go#L99-L100 that sets the `InsecureSkipVerify` similar to https://github.com/mondoohq/cnquery/blob/main/providers/os/resources/discovery/container_registry/registry.go#L51-L55

### PR DESCRIPTION
**Pull request by imilchev**
Changed the `insecure` flag to bool. No idea why it was a string. Also added an HTTP client to the host connection, so we define all the properties in 1 place and re-use them where needed.

```
╰─ cnspec shell host https://localhost --insecure
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ connected to Network Host
  ___ _ __  ___ _ __   ___  ___ 
 / __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
 \___|_| |_|___/ .__/ \___|\___|
   mondoo™     |_|              
cnspec> http.get
http.get: http.get url=url id = https://localhost:443 statusCode=200
```

Fixes #3995

### CODE REVIEW

File: providers/network/connection/connection.go [hunk 1]
```diff
@@ -4,21 +4,47 @@
...
+		transport.TLSClientConfig = &tls.Config{
+			InsecureSkipVerify: true,
+		}
+	}
+
 	return &HostConnection{
 		Connection: plugin.NewConnection(id, asset),
 		Conf:       conf,
 		asset:      asset,
+		httpClient: &http.Client{Transport: transport},
```
Comment (chris-rock) [inline providers/network/connection/connection.go:47]: nice idea to attach the http client to the connection

File: providers/network/resources/http.go [hunk 2]
```diff
@@ -96,7 +96,8 @@ func (x *mqlHttpGet) do() error {
 		return errors.New("missing URL for http.get")
 	}
 
-	resp, err := http.Get(x.Url.Data.String.Data)
+	conn := x.MqlRuntime.Connection.(*connection.HostConnection)
+	resp, err := conn.Client().Get(x.Url.Data.String.Data)
```
Comment (chris-rock) [inline providers/network/resources/http.go:100]: Nice and clean.

**Review by chris-rock — APPROVED** [review]
Thank you @imilchev
