### PR TITLE
🧹 Pass loglevel to plugin

### LINKED ISSUE #1763: log level is not transferred to v9 plugins
**Describe the bug**
I see different output when running a plugin as builtin vs. using it as external plugin.

external:
```
cnquery run local --discover container -c "asset.eol" --verbose 
DBG using provider os with connector local
DBG no need to update provider last-refresh=16.313862145s provider=os
DBG running provider plugin path=/home/christian/.config/mondoo/providers/os/os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
DBG resolved 1 assets
! failure in machineID detector error="cannot determine platform uuid: file does not exist"
DBG starting query execution qrid=cH/IFemhkHk=
DBG finished query execution qrid=cH/IFemhkHk=
DBG jOdxwbshpGcTHNTjb+wr69Jv7sKtmoTLMKtASD4d/uZOohRXLxa9AuW/KaJhc14IAbsjcgr2CgGT6gXlPJmv8g== finished
DBG graph has received all datapoints
asset.eol: asset.eol date=2026-06-30 02:00:00 +0200 CEST
```

builtin:
```
DBG using provider os with connector local
! using builtin provider for os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
DBG local> run command uname -s
2
DBG local> run command uname -m
DBG platform> detected os family=["debian","linux","unix","os"] platform=ubuntu
DBG local> run command hostname
DBG detected asset asset=
DBG start discovery for docker engine
DBG discovered container container=b5f080861f89c9e61ff627c66c24295607859c4025d0b1ba6aef0115a924d973
→ running container search completed container=1
DBG resolved 1 assets
! using builtin provider for os
DBG found running container b5f080861f89c9e61ff627c66c24295607859c4025d0b1ba6aef0115a924d973
DBG docker> server version serverVersion={"ApiVersion":"1.43","Arch":"amd64","BuildTime":"2023-09-04T12:31:44.000000000+00:00","Components":[{"Details":{"ApiVersion":"1.43","Arch":"amd64","BuildTime":"2023-09-04T12:31:44.000000000+00:00","Experimental":"false","GitCommit":"1a79695","GoVersion":"go1.20.7","KernelVersion":"6.2.0-32-generic","MinAPIVersion":"1.12","Os":"linux"},"Name":"Engine","Version":"24.0.6"},{"Details":{"GitCommit":"8165feabfdfe38c65b599c4993d227328c231fca"},"Name":"containerd","Version":"1.6.22"},{"Details":{"GitCommit":"v1.1.8-0-g82f18fe"},"Name":"runc","Version":"1.1.8"},{"Details":{"GitCommit":"de40ad0"},"Name":"docker-init","Version":"0.19.0"}],"GitCommit":"1a79695","GoVersion":"go1.20.7","KernelVersion":"6.2.0-32-generic","MinAPIVersion":"1.12","Os":"linux","Platform":{"Name":"Docker Engine - Community"},"Version":"24.0.6"}
DBG initialize client authentication issuer=mondoo/ams kid=//agents.api.mondoo.app/spaces/dazzling-golick-767384/serviceaccounts/2AyMRoi8pfJa6gOqq16QWstmKPK
DBG docker> run command command="uname -s"
DBG docker> run command command="uname -m"
...
```

**To Reproduce**

1. Run the same command with debug enabled with an external plugin and a builtin plugin
4. Compare the output

**Expected behavior**
I'd expect to see the same output for external and builtin.

### PR DESCRIPTION
**Pull request by czunker**
This passes the cnquery loglevel down to the plugin.

Fixes #1763

### CODE REVIEW

File: providers-sdk/v1/plugin/start.go [hunk 1]
```diff
@@ -46,6 +47,15 @@ type Connector struct {
 func Start(args []string, impl ProviderPlugin) {
 	logger.CliCompactLogger(logger.LogOutputWriter)
 	zerolog.SetGlobalLevel(zerolog.WarnLevel)
+	if len(args) > 1 {
```
Comment (chris-rock) [inline providers-sdk/v1/plugin/start.go]: we would need a proper flag for that, otherwise it will be difficult to add more flags without making a breaking change when we want to change the order

**Review by chris-rock — CHANGES_REQUESTED** [review]

File: providers-sdk/v1/plugin/start.go (hunk 1 above)
Comment (czunker) [reply providers-sdk/v1/plugin/start.go]: I changed both to flags.

File: providers-sdk/v1/plugin/start.go [hunk 2]
```diff
@@ -45,7 +47,20 @@ type Connector struct {
 
 func Start(args []string, impl ProviderPlugin) {
 	logger.CliCompactLogger(logger.LogOutputWriter)
-	zerolog.SetGlobalLevel(zerolog.WarnLevel)
+
+	runAsPlugin := true
```
Comment (chris-rock) [inline providers-sdk/v1/plugin/start.go]: Are we doing anything with this flag?

File: providers/coordinator.go [hunk 3]
```diff
@@ -197,8 +198,7 @@ func (c *coordinator) Start(id string, isEphemeral bool, update UpdateProvidersC
 		}
 	}
 
-	pluginCmd := exec.Command(provider.binPath(), "run_as_plugin")
-	log.Debug().Str("path", pluginCmd.Path).Msg("running provider plugin")
+	pluginCmd := exec.Command(provider.binPath(), []string{"--run-as-plugin", "--log-level", zerolog.GlobalLevel().String()}...)
```
Comment (chris-rock) [inline providers/coordinator.go]: This would not be backwards-compatible with older plugin versions. Any reason why not keep the subcommand "run_as_plugin"?

Comment (czunker) [reply providers/coordinator.go]: I didn't read it as subcommand, but thought it was another arg. Reverted this part.

File: providers-sdk/v1/plugin/start.go (hunk 2 above)
Comment (czunker) [reply providers-sdk/v1/plugin/start.go]: Reverted, as it is no longer needed.

**Review by arlimus — APPROVED** [review]
Great to see log levels respected
