### PR TITLE
✨ gcp gcr repository scanning v9

### LINKED ISSUE #1648: `gcp gcr` scan with project does not work as described
**Describe the bug**
```
cnquery run gcp gcr mondoo-dev-XYZ --repository ubuntu -c "container.image" --verbose 
DBG parsing asset asset-type=14 provider=CONTAINER_REGISTRY
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
DBG run resolver resolver="Container Registry Discover" resolver-id=cr
→ fetch meta information from container registry registry=gcr.iomondoo-dev-XYZ/ubuntu
x could not fetch container images error="Get \"https://gcr.iomondoo-dev-XYZ/v2/\": dial tcp: lookup gcr.iomondoo-dev-XYZ on 127.0.0.53:53: no such host"
→ resolved assets resolved-assets=0
x could not resolve asset error="Get \"https://gcr.iomondoo-dev-XYZ/v2/\": dial tcp: lookup gcr.iomondoo-dev-XYZ on 127.0.0.53:53: no such host" asset=gcr.iomondoo-dev-XYZ/ubuntu
FTL failed to run query error="could not find an asset that we can connect to"
```

There is a slash missing in the URL: `https://gcr.iomondoo-dev-XYZ/v2/`

When you add the slash to the project id, it works.

**To Reproduce**

1. Run the above command
2. Note the error

**Expected behavior**
The command should scan the gcr repository.

**Desktop (please complete the following information):**

- cnquery v8.25.0

### PR DESCRIPTION
**Pull request by czunker**
Fixes #1648 and ports the v8 connection to v9

### CODE REVIEW

File: providers/gcp/resources/discovery/gcr/gcr.go [hunk 1]
```diff
@@ -52,21 +49,22 @@ func (a *GcrImages) ListRepository(repository string, recursive bool) ([]*asset.
 			repoURL := repo.String()
 			imageUrl := repoURL + "@" + digest
 
-			asset := &asset.Asset{
+			asset := &inventory.Asset{
 				PlatformIds: []string{MondooContainerImageID(digest)},
 				Name:        containerid.ShortContainerImageID(digest),
```
Comment (imilchev) [inline providers/gcp/resources/discovery/gcr/gcr.go]: this looks like the k8s container-image discovery. I think we should match the approach and just return an asset with a connection config and nothing else. We should let the os provider fill in the platform IDs, name, etc.

File: providers/gcp/resources/discovery/gcr/gcr.go
Comment (imilchev) [inline providers/gcp/resources/discovery/gcr/gcr.go:1]: do we need to put this in a separate folder? the rest of the discovery is all in the `discovery.go`

File: providers/gcp/resources/discovery/gcr/gcr.go [hunk 2]
```diff
@@ -112,13 +110,8 @@ func (a *GcrImages) ListRepository(repository string, recursive bool) ([]*asset.
...
-	assets := []*asset.Asset{}
-	// repoAssets, err := a.ListRepository("index.docker.io/mondoo/client", false)
-	// if err == nil && repoAssets != nil {
-	// 	assets = append(assets, repoAssets...)
-	// }
-	// return assets, nil
+func (a *GcrImages) List() ([]*inventory.Asset, error) {
+	assets := []*inventory.Asset{}
 
 	resSrv, err := cloudresourcemanager.NewService(context.Background())
```
Comment (imilchev) [inline providers/gcp/resources/discovery/gcr/gcr.go]: Can we do this via MQL?

File: providers/gcp/resources/discovery/gcr/resolver_gcr.go [hunk 3]
```diff
@@ -20,18 +18,19 @@ func (r *GcrResolver) Name() string {
...
+	return []string{"auto", "all"}
 }
 
-func (r *GcrResolver) Resolve(ctx context.Context, root *asset.Asset, t *providers.Config, credsResolver vault.Resolver, sfn common.QuerySecretFn, userIdDetectors ...providers.PlatformIdDetector) ([]*asset.Asset, error) {
-	resolved := []*asset.Asset{}
-	repository := t.Host
+// func (r *GcrResolver) Resolve(ctx context.Context, root *inventory.Asset, t *inventory.Config, credsResolver vault.Resolver, sfn common.QuerySecretFn, userIdDetectors ...providers.PlatformIdDetector) ([]*inventory.Asset, error) {
+func (r *GcrResolver) Resolve(ctx context.Context, root *inventory.Asset, conf *inventory.Config, credsResolver vault.Resolver) ([]*inventory.Asset, error) {
+	resolved := []*inventory.Asset{}
+	repository := conf.Host
```
Comment (imilchev) [inline providers/gcp/resources/discovery/gcr/resolver_gcr.go]: i guerss this code can go in `discovery.go`

File: providers/gcp/resources/discovery/gcr/gcr.go (hunk 1 above)
Comment (czunker) [reply providers/gcp/resources/discovery/gcr/gcr.go]: :thinking: Strange. I used your PR as an example and removed this. Not sure why it is back in.

Thanks for catching this.

File: providers/gcp/resources/discovery/gcr/gcr.go
Comment (czunker) [reply providers/gcp/resources/discovery/gcr/gcr.go:1]: Done

File: providers/gcp/resources/discovery/gcr/resolver_gcr.go (hunk 3 above)
Comment (czunker) [reply providers/gcp/resources/discovery/gcr/resolver_gcr.go]: Done

File: providers/gcp/resources/discovery/gcr/gcr.go (hunk 2 above)
Comment (czunker) [reply providers/gcp/resources/discovery/gcr/gcr.go]: Perhaps...

But this would require adding multiple MQL resources. And I'd prefer to actually get rid of the repository resource we currently have: https://github.com/mondoohq/cnquery/issues/1651

This command is only about the images. We do not care about the rest at this point.

File: providers/gcp/resources/discovery.go [hunk 4]
```diff
@@ -362,3 +384,127 @@ func cloneConfig(invConf *inventory.Config) *inventory.Config {
...
+	if err != nil {
+		return nil, err
+	}
+	return imgs, nil
+}
+
+// List uses your GCP credentials to iterate over all your projects to identify potential repos
+func (a *GcrImages) List() ([]*inventory.Asset, error) {
+	assets := []*inventory.Asset{}
+
```
Comment (vjeffrey) [inline providers/gcp/resources/discovery.go:479]: why not use the resource directly here instead of calling the api?

Comment (czunker) [reply providers/gcp/resources/discovery.go:479]: My understanding is, we do not have these resources.

At the end, `gcp gcr` and `container registry` commands, both create `container.image` resources, but how we get there is different.

`gcp gcr` does not use a container registry API, but the GCP API. We do not have the intermediate resources `gcp.gcr` and `gcp.gcr.repository`. As I understand this provider, we do not care about these.

So, we start by iterating over all repositories which are present in a GCP project. We take these repositories and iterate over all the images which in these repositories. These images end up as resources, but nothing in between.

File: providers/gcp/resources/discovery/gcr/gcr.go (hunk 2 above)
Comment (czunker) [reply providers/gcp/resources/discovery/gcr/gcr.go]: As @vjeffrey had the same question, I dug a bit deeper. Now, I think it isn't possible: https://github.com/mondoohq/cnquery/pull/1650#discussion_r1319335451
