### PR TITLE
🐛 Fix platform IDs for operator manifests

### LINKED ISSUE #2818: cnquery k8s: `asset K8s Manifest mondoo-operator-manifests and mondoo-operator/mondoo-operator-controller-manager have the same platform id`
**Describe the bug**
```
FTL failed to run scan error="asset K8s Manifest mondoo-operator-manifests and mondoo-operator/mondoo-operator-controller-manager have the same platform id //platformid.api.mondoo.app/runtime/k8s/uid/48878e43bc66a279f8a38c5b3974195152d5082147de5231d997f278348cec92"
```

This happened in our mondoo-operator pipeline:
https://github.com/mondoohq/mondoo-operator/actions/runs/7192977744/job/19590656939?pr=971

**To Reproduce**

I assume this can be reproduced by manually scanning the manifest from the mondoo-operator repo.

**Expected behavior**
platformIDs should be different.

### PR DESCRIPTION
**Pull request by czunker**
Fixes #2818

### CODE REVIEW

**Comment by czunker** [comment]
Now the platform IDs are different again:
```
cnquery run k8s ../mondoo-operator/mondoo-operator-manifests.yaml -c "asset{ name ids platform }"
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
asset: {
  platform: "k8s-manifest"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/39ecb5473a665750ddc586404ef65063a3b6adf9d1df51d4d4ca09d48516ad25"
  ]
  name: "K8s Manifest mondoo-operator-manifests"
}
asset: {
  platform: "k8s-deployment"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/39ecb5473a665750ddc586404ef65063a3b6adf9d1df51d4d4ca09d48516ad25/namespace/mondoo-operator/deployments/name/mondoo-operator-controller-manager"
  ]
  name: "mondoo-operator/mondoo-operator-controller-manager"
}
```

File: providers/k8s/connection/manifest/connection.go [hunk 1]
```diff
@@ -81,12 +81,6 @@ func NewConnection(id uint32, asset *inventory.Asset, opts ...Option) (shared.Co
 		asset.Name = clusterName
 	}
 
-	platformId, err := c.AssetId()
```
Comment (czunker) [inline providers/k8s/connection/manifest/connection.go:84]: We already do this during discovery:
https://github.com/mondoohq/cnquery/blob/main/providers/k8s/resources/discovery.go#L118-L128

**Review by imilchev — APPROVED** [review]
just tested this and works correctly! Nice to add tests since this specific feature broke more than once already!
