### PR TITLE
🐛 Fix asset data for multiple assets

### LINKED ISSUE #1654: When discovering multiple assets, all show the same data
**Describe the bug**
When we discover multiple assets, all assets show the same `asset` data in the output.

E.g. container-images:
```
cnquery run container registry gcr.io/mondoo-dev-262313/ubuntu -c "asset{ name platform ids kind runtime title }" --verbose 
...
DBG resolved 4 assets
DBG starting query execution qrid=Gu4E/am/vH4=
DBG finished query execution qrid=Gu4E/am/vH4=
DBG 6itM5rJMwe6uQJbyBX0dKGe97IZVIL4koKv8axMp+gctOeKltE7Y6g0YdUcPFe20H7RF0sgbT+7wcjv8b2QwGw== finished
DBG graph has received all datapoints
asset: {
  kind: "container-image"
  title: "Ubuntu 16.04.6 LTS, Docker Image"
  platform: "ubuntu"
  runtime: "docker-image"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/docker/images/a98d9dcf3a34b2b78e78c61d003eb4d7a90d30fd54451686e2f0bd2ef5f602ac"
    1: "localhost.localdomain"
  ]
  name: "gcr.io/mondoo-dev-262313/ubuntu@a98d9dcf3a34"
}
DBG starting query execution qrid=Gu4E/am/vH4=
DBG finished query execution qrid=Gu4E/am/vH4=
DBG 6itM5rJMwe6uQJbyBX0dKGe97IZVIL4koKv8axMp+gctOeKltE7Y6g0YdUcPFe20H7RF0sgbT+7wcjv8b2QwGw== finished
DBG graph has received all datapoints
asset: {
  kind: "container-image"
  title: "Ubuntu 16.04.6 LTS, Docker Image"
  platform: "ubuntu"
  runtime: "docker-image"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/docker/images/a98d9dcf3a34b2b78e78c61d003eb4d7a90d30fd54451686e2f0bd2ef5f602ac"
    1: "localhost.localdomain"
  ]
  name: "gcr.io/mondoo-dev-262313/ubuntu@a98d9dcf3a34"
}
...
```

E.g. k8s namespaces:
```
cnquery_main run k8s --discover namespaces -c 'asset{ platform name ids }' --verbose 
...
DBG resolved 5 assets
DBG starting query execution qrid=glQmIa11rxk=
DBG finished query execution qrid=glQmIa11rxk=
DBG wjyPVVpnoN3v2zuymNQlrIYnhN3Yc9hxr8Ov8Zfg2kGRVT+7qwkOCTJgJFpP0uWS7pSGRV0vjqSntan9epDR4Q== finished
DBG graph has received all datapoints
asset: {
  platform: "k8s-namespace"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8/namespace/cert-manager/uid/ca1cba98-56f9-45ae-9bef-5e412a90ee2e"
  ]
  name: "cert-manager"
}
DBG starting query execution qrid=glQmIa11rxk=
DBG finished query execution qrid=glQmIa11rxk=
DBG wjyPVVpnoN3v2zuymNQlrIYnhN3Yc9hxr8Ov8Zfg2kGRVT+7qwkOCTJgJFpP0uWS7pSGRV0vjqSntan9epDR4Q== finished
DBG graph has received all datapoints
asset: {
  platform: "k8s-namespace"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8/namespace/cert-manager/uid/ca1cba98-56f9-45ae-9bef-5e412a90ee2e"
  ]
  name: "cert-manager"
}
...
```

**To Reproduce**

1. Check out latest main
2. Run one of the above queries
3. Note the error

**Expected behavior**
I'd expect to see the data matching the asset.

### PR DESCRIPTION
**Pull request by czunker**
Thanks to @preslavgerchev , we found this.

Fixes #1654

### CODE REVIEW

**Comment by czunker** [comment]
This now returns distinct data for each asset:
```
cnquery run container registry gcr.io/mondoo-dev-262313/ubuntu -c "asset{ name platform ids kind runtime title }"                                                                  ✔ │ 16:18:00 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
asset: {
  kind: "container-image"
  title: "Ubuntu 16.04.6 LTS, Docker Image"
  platform: "ubuntu"
  runtime: "docker-image"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/docker/images/a98d9dcf3a34b2b78e78c61d003eb4d7a90d30fd54451686e2f0bd2ef5f602ac"
    1: "localhost.localdomain"
  ]
  name: "gcr.io/mondoo-dev-262313/ubuntu@a98d9dcf3a34"
}
asset: {
  kind: "container-image"
  title: "Ubuntu 18.04.4 LTS, Docker Image"
  platform: "ubuntu"
  runtime: "docker-image"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/docker/images/0925d086715714114c1988f7c947db94064fd385e171a63c07730f1fa014e6f9"
    1: "localhost.localdomain"
  ]
  name: "gcr.io/mondoo-dev-262313/ubuntu@0925d0867157"
}
asset: {
  kind: "container-image"
  title: "Ubuntu 19.04, Docker Image"
  platform: "ubuntu"
  runtime: "docker-image"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/docker/images/61844ceb1dd55aa110ca578bd4a042200bc64bb5d702c9a19b9fb90409565da0"
    1: "localhost.localdomain"
  ]
  name: "gcr.io/mondoo-dev-262313/ubuntu@61844ceb1dd5"
}
asset: {
  kind: "container-image"
  title: "Ubuntu 18.04.4 LTS, Docker Image"
  platform: "ubuntu"
  runtime: "docker-image"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/docker/images/e5dd9dbb37df5b731a6688fa49f4003359f6f126958c9c928f937bec69836320"
    1: "localhost.localdomain"
  ]
  name: "gcr.io/mondoo-dev-262313/ubuntu@e5dd9dbb37df"
}
```

Or:
```
cnquery run k8s --discover namespaces -c 'asset{ platform name ids }'                                                                                                              ✔ │ 16:17:06 
! cannot determine latest version of provider 'k8s'
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
asset: {
  platform: "k8s-namespace"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8/namespace/cert-manager/uid/ca1cba98-56f9-45ae-9bef-5e412a90ee2e"
  ]
  name: "cert-manager"
}
asset: {
  platform: "k8s-namespace"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8/namespace/default/uid/dea57938-255a-4b7a-b5ac-b3a59b1a2dbf"
  ]
  name: "default"
}
asset: {
  platform: "k8s-namespace"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8/namespace/kube-node-lease/uid/675d3c10-350c-4dd6-bcbd-d1711cfb52d9"
  ]
  name: "kube-node-lease"
}
asset: {
  platform: "k8s-namespace"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8/namespace/kube-public/uid/9e0a0b75-4b9e-4f29-8060-323a16bf0e5c"
  ]
  name: "kube-public"
}
asset: {
  platform: "k8s-namespace"
  ids: [
    0: "//platformid.api.mondoo.app/runtime/k8s/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8/namespace/kube-system/uid/3b922b13-754a-48c6-a9a5-7df8148ecbc8"
  ]
  name: "kube-system"
}

```

File: apps/cnquery/cmd/plugin.go [hunk 1]
```diff
@@ -109,10 +109,12 @@ func (c *cnqueryPlugin) RunQuery(conf *run.RunQueryConfig, runtime *providers.Ru
 
 	for i := range assets {
 		connectAsset := assets[i]
-		if err := runtime.DetectProvider(connectAsset); err != nil {
+		// FIXME: I assume we need to transfer settings like recording, etc. to the new runtime
+		connectAssetRuntime := providers.Coordinator.NewRuntime()
```
Comment (czunker) [inline apps/cnquery/cmd/plugin.go:113]: This comment led us to believe this might be the correct solution: https://github.com/mondoohq/cnquery/blob/1c014c0d3c383c0344e340ba75a0863e3843e6b0/providers/runtime.go#L20-L21

File: apps/cnquery/cmd/plugin.go [hunk 2]
```diff
@@ -109,10 +109,12 @@ func (c *cnqueryPlugin) RunQuery(conf *run.RunQueryConfig, runtime *providers.Ru
 
 	for i := range assets {
 		connectAsset := assets[i]
-		if err := runtime.DetectProvider(connectAsset); err != nil {
+		// FIXME: I assume we need to transfer settings like recording, etc. to the new runtime
```
Comment (czunker) [inline apps/cnquery/cmd/plugin.go:112]: Perhaps we need a clone function like we now also have for the conf inside k8s and was providers?

**Review by vjeffrey — APPROVED** [review]
thank you, this is working well for me, lets get it in and follow up as needed
