### PR TITLE
🐛 Prevent k8s scan panic

### LINKED ISSUE #1749: V9: segfault scanning k8s
**Describe the bug**
```
cnquery scan k8s --log-level trace
DBG using provider k8s with connector k8s
DBG no need to update provider last-refresh=40m34.54718321s provider=k8s
DBG running provider plugin path=/Users/tsmith/.config/mondoo/providers/k8s/k8s
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
DBG adding 83 discovered asset(s)
DBG running provider plugin path=/Users/tsmith/.config/mondoo/providers/os/os
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x98 pc=0x10146f05c]

goroutine 1 [running]:
go.mondoo.com/cnquery/explorer/scan.(*LocalScanner).distributeJob(0x140008db230, 0x140008b0fc0, {0x1019d14f8, 0x140008db260}, 0x14000752c40)
	/Users/tsmith/dev/cnquery/explorer/scan/local_scanner.go:241 +0x7ac
go.mondoo.com/cnquery/explorer/scan.(*LocalScanner).Run(0x1019d14c0?, {0x1019d14f8?, 0x140008db260?}, 0x10237e7c0?)
	/Users/tsmith/dev/cnquery/explorer/scan/local_scanner.go:92 +0x50
go.mondoo.com/cnquery/apps/cnquery/cmd.RunScan(0x140008df480)
	/Users/tsmith/dev/cnquery/apps/cnquery/cmd/scan.go:287 +0x364
go.mondoo.com/cnquery/apps/cnquery/cmd.glob..func21(0x0?, 0x140002f9b00?, 0x23?)
	/Users/tsmith/dev/cnquery/apps/cnquery/cmd/scan.go:119 +0x94
go.mondoo.com/cnquery/cli/providers.setConnector.func2(0x14000347c00?, {0x14000385ce0?, 0x0, 0x2})
	/Users/tsmith/dev/cnquery/cli/providers/providers.go:336 +0xc8c
github.com/spf13/cobra.(*Command).execute(0x1400039b500, {0x14000385cc0, 0x2, 0x2})
	/Users/tsmith/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x1023334c0)
	/Users/tsmith/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/tsmith/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnquery/apps/cnquery/cmd.Execute()
	/Users/tsmith/dev/cnquery/apps/cnquery/cmd/root.go:71 +0x15c
main.main()
	/Users/tsmith/dev/cnquery/apps/cnquery/cnquery.go:9 +0x1c
```

### PR DESCRIPTION
**Pull request by czunker**
When scanning k8s with container image discovery, it paniced. That happened because asset data was missing.

Fixes #1749

### CODE REVIEW

**Comment by czunker** [comment]
@imilchev / @arlimus Could you please have a look? You solved something similar for `run` and `shell`:

https://github.com/mondoohq/cnquery/commit/ad6e646bf65041c10d163ab7b6cdcfbb10b60713 and https://github.com/mondoohq/cnquery/pull/1646

**Comment by czunker** [comment]
Working now:
```
cnquery scan k8s --discover container-images                                                                     ✔ │ 10:24:58 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets

 registry.k8s.io/kube-controller-manager@c4765f949306 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
 registry.k8s.io/kube-proxy@ce9abe867450              ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
 registry.k8s.io/kube-scheduler@9c58009453cf          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
 gcr.io/k8s-minikube/storage-provisioner@c4c05d6ad6c0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
 registry.k8s.io/coredns/coredns@be7652ce0b43         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
 registry.k8s.io/etcd@8ae03c7bbd43                    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
 registry.k8s.io/kube-apiserver@dcf39b4579f8          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%

 7/7 scanned                                          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%

Data (7 assets)
===============

Asset: registry.k8s.io/etcd@8ae03c7bbd43
----------------------------------------

asset-overview-assetarch:
asset.arch: "amd64"
...
```

File: providers/aws/provider/provider.go [hunk 1]
```diff
@@ -13,16 +13,12 @@ import (
...
-	osconnection "go.mondoo.com/cnquery/providers/os/connection"
 	"go.mondoo.com/cnquery/providers/os/connection/shared"
-	"go.mondoo.com/cnquery/providers/os/detector"
 )
 
 const (
-	defaultConnection           uint32 = 1
-	DefaultConnectionType              = "aws"
-	SshConnectionType                  = "ssh"
-	RegistryImageConnectionType        = "registry-image"
```
Comment (czunker) [inline providers/aws/provider/provider.go:25]: This removal is also part of https://github.com/mondoohq/cnquery/pull/1707. But I removed even more here.

I had to fix this here otherwise, the AWS provider would take over the provider for some images.

File: explorer/scan/local_scanner.go [hunk 2]
```diff
@@ -188,15 +188,11 @@ func (s *LocalScanner) distributeJob(job *Job, ctx context.Context, upstream *up
...
 		}
-		inventorySpec := runtime.Provider.Connection
-		if inventorySpec.Inventory != nil &&
-			inventorySpec.Inventory.Spec != nil &&
-			inventorySpec.Inventory.Spec.Assets != nil {
-			log.Debug().Msgf("adding %d discovered asset(s)", len(runtime.Provider.Connection.Inventory.Spec.Assets))
-			assetCandidates = append(assetCandidates, inventorySpec.Inventory.Spec.Assets...)
-		} else {
-			assetCandidates = append(assetCandidates, runtime.Provider.Connection.Asset)
+		processedAssets, err := providers.ProcessAssetCandidates(runtime, runtime.Provider.Connection, upstream, "")
```
Comment (czunker) [inline explorer/scan/local_scanner.go:191]: That's the actual fix to prevent the panic.

**Comment by vjeffrey** [comment]
this all seems correct, i just wanna spin it up locally before merging - doing that now

**Review by vjeffrey — APPROVED** [review]
