### PR TITLE
🐛 fix scan --help duplicates scan targets

### LINKED ISSUE #2118: cnquery scan --help duplicates scan targets
**Describe the bug**
Running `cnquery scan --help` shows duplicate scan targets.

```
Available Commands:
  aws         Scan aws account
  container   Scan a running container or container image
  container   Scan a running container or container image
  docker      Scan a running docker or docker image
  docker      Scan a running docker or docker image
  filesystem  Scan a mounted file system target.
  filesystem  Scan a mounted file system target.
  filesystem  Scan a mounted file system target.
  filesystem  Scan a mounted file system target.
  gcp         Scan GCP Cloud
  k8s         Scan a Kubernetes cluster or local manifest file(s).
  k8s         Scan a Kubernetes cluster or local manifest file(s).
  local       Scan your local system
  local       Scan your local system
  mock        Scan use a recording without an active connection
  okta        Scan Okta
  ssh         Scan a remote system via SSH
  ssh         Scan a remote system via SSH
  terraform   Scan a terraform hcl file or directory.
  vagrant     Scan a Vagrant host
  vagrant     Scan a Vagrant host
  winrm       Scan a remote system via WinRM
  winrm       Scan a remote system via WinRM
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

### PR DESCRIPTION
**Pull request by mariuskimmina**
Closes #2118 

Each target that had an Alias, such as k8s and kubernetes, would show up once for each alias in `cnquery scan --help`.

Before:
```
Available Commands:
  container   Scan a running container or container image
  docker      Scan a running docker or docker image
  filesystem  Scan a mounted file system target test.
  filesystem  Scan a mounted file system target test.
  k8s         Scan a Kubernetes cluster or local manifest file(s).
  k8s         Scan a Kubernetes cluster or local manifest file(s).
  local       Scan your local system
  mock        Scan use a recording without an active connection
  ssh         Scan a remote system via SSH
  vagrant     Scan a Vagrant host
  winrm       Scan a remote system via WinRM
```

After:
```
Available Commands:
  container   Scan a running container or container image
  docker      Scan a running docker or docker image
  filesystem  Scan a mounted file system target test.
  k8s         Scan a Kubernetes cluster or local manifest file(s).
  local       Scan your local system
  mock        Scan use a recording without an active connection
  ssh         Scan a remote system via SSH
  vagrant     Scan a Vagrant host
  winrm       Scan a remote system via WinRM
```

I verified that using the aliases also still works as expected.
I am unsure if there was another reason for us to add these connector copies, so far I haven't found any side effects.

### CODE REVIEW

File: cli/providers/providers.go [hunk 1]
```diff
@@ -139,11 +139,6 @@ func attachProvidersToCmd(existing providers.Providers, cmd *Command) {
 		for j := range provider.Connectors {
 			conn := provider.Connectors[j]
 			attachConnectorCmd(provider.Provider, &conn, cmd)
-			for k := range conn.Aliases {
```
Comment (czunker) [inline cli/providers/providers.go:142]: This was needed, to get aliases work with plugins: https://github.com/mondoohq/cnquery/pull/1696/commits/24ee6f5178d9f8dd83dd865fcdd7cf9ca1d65587

Need to double check, whether this still works.

Comment (czunker) [reply cli/providers/providers.go:142]: Seems, this is no longer needed. Gave it a try with filesystem/fs and kubernetes/k8s. Both work.

**Review by czunker — APPROVED** [review]
LGTM. Thanks @mariuskimmina
