### PR TITLE
⭐️ k8s namespace-scoped scanning

### LINKED ISSUE #1022: k8s scan tries to list all namespaces despite namespace filter
**Describe the bug**
a user reported that the api was erroring because we try to request all namespaces despite the filter. it appears we aren't passing the filters through to the api call, and are instead filtering listing all namespaces. this causes an issue for users for whom the namespace filter is more of an rbac requirement than a desire
https://github.com/mondoohq/cnquery/blob/main/motor/discovery/k8s/resolver.go#L108

### PR DESCRIPTION
**Pull request by imilchev**
- [x] Split k8s cluster and namespace resolver
- [x] When `--namespaces` and listing namespaces is not working, attempt getting those specific namespaces
- [x] Adjust the k8s provider to be able to work with a cluster and namespace root (requires adjusting the platformID)
- [x] Make sure k8s MQL resources for a namespace root, list only the resources in that namespace (not globally)
- [x] Test with the mondoo-operator (node scan, cluster scan, admission controller)

Fixes #1022 

```
./cnquery run k8s --namespaces default -c "k8s.pods" --discover namespaces                                                                                                                                                                             
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
k8s.pods: [
  0: k8s.pod namespace="default" name="nginx" created=2023-03-14 16:59:07 +0100 CET
]
```

Best is to test this by creating a new k8s user and giving it access only to 1 namespace. I used [this tutorial](https://medium.com/@HoussemDellai/rbac-with-kubernetes-in-minikube-4deed658ea7b) for creating a new minikube user. You can use this role and bind it to the test user:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-admin
  namespace: default
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

### CODE REVIEW

**Comment by scottford-io** [comment]
@imilchev thanks for adding this. Given the flag is labeled `--namespaces`, are we going to support scanning multiple namespaces? 🤔  If not, should the flag be `--namespace` instead?

**Comment by imilchev** [comment]
> @imilchev thanks for adding this. Given the flag is labeled `--namespaces`, are we going to support scanning multiple namespaces? 🤔 If not, should the flag be `--namespace` instead?

We support scanning multiple namespaces at a time. The flag has been there for a while. It just worked only if you have global cluster access. With this change it works also if you have access to just those namespaces

File: motor/providers/k8s/platform.go [hunk 1]
```diff
@@ -17,3 +24,11 @@ func NewPlatformWorkloadId(clusterIdentifier, workloadType, namespace, name stri
 	platformIdentifier += "/" + workloadType + "s" + "/name/" + name
 	return platformIdentifier
 }
+
+func NewNamespacePlatformId(clusterIdentifier, name string) string {
+	if clusterIdentifier == "" {
+		return fmt.Sprintf("//platformid.api.mondoo.app/runtime/k8s/namespace/%s", name)
```
Comment (czunker) [inline motor/providers/k8s/platform.go:30]: I think this will prevent us from scanning a namespace with the same name in different clusters. The platformID needs to be unique across assets.

I'm quite sure, but I'll try this out.

File: motor/providers/k8s/api_provider.go [hunk 2]
```diff
@@ -201,9 +197,9 @@ func (t *apiProvider) SupportedResourceTypes() (*resources.ApiResourceIndex, err
 
 func (t *apiProvider) Resources(kind string, name string, namespace string) (*ResourceResult, error) {
 	ctx := context.Background()
-	ns := t.namespace
+	// ns := t.namespace
```
Comment (czunker) [inline motor/providers/k8s/api_provider.go]: nit: We can remove this completely.

File: motor/discovery/k8s/resolver_namespace.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+		DiscoveryClusters,
+		DiscoveryPods,
+		DiscoveryJobs,
+		DiscoveryCronJobs,
+		DiscoveryStatefulSets,
+		DiscoveryDeployments,
+		DiscoveryReplicaSets,
+		DiscoveryDaemonSets,
+		DiscoveryContainerImages,
+		DiscoveryAdmissionReviews,
```
Comment (czunker) [inline motor/discovery/k8s/resolver_namespace.go:42]: What about these non-namespaced discovery options?

How does the namespace filter here work in combination with the operator? I'll have to double-check that.

File: motor/providers/k8s/platform.go (hunk 1 above)
Comment (czunker) [reply motor/providers/k8s/platform.go:30]: Ok, it does not error, but the assets get overridden.

image

resource version and the uuid change in the backend.

File: motor/discovery/k8s/resolver_namespace.go (hunk 3 above)
Comment (czunker) [reply motor/discovery/k8s/resolver_namespace.go:42]: I currently suspect this would break the admission webhook: https://github.com/mondoohq/mondoo-operator/blob/main/cmd/mondoo-operator/webhook/cmd.go#L80

I'm not sure how to test this.

File: motor/providers/k8s/platform.go (hunk 1 above)
Comment (imilchev) [reply motor/providers/k8s/platform.go:30]: Will need to add the ns UID to the platform too to make this work

File: motor/discovery/k8s/resolver_namespace.go (hunk 3 above)
Comment (imilchev) [reply motor/discovery/k8s/resolver_namespace.go:42]: It shouldn't break the admission controller. It doesn't use ns filtering. I can test it once we have settled on the implementation. Let's resolve all comments on this PR and as a last step before merging I will check it with the operator. Will add this to the list of tasks at the top

**Comment by joelddiaz** [comment]
> @imilchev thanks for adding this. Given the flag is labeled `--namespaces`, are we going to support scanning multiple namespaces? thinking If not, should the flag be `--namespace` instead?

Should just be a comma-separated list of namespaces https://github.com/mondoohq/cnquery/blob/9177e86c4a0add14bbb8bd7fb86c532e2ca4db14/motor/discovery/k8s/resolver.go#L90-L93

File: motor/discovery/k8s/resolver_namespace.go (hunk 3 above)
Comment (czunker) [reply motor/discovery/k8s/resolver_namespace.go:42]: I managed to test it with a local minkube. Works as you expected. Nice!

Webhook filters objects before sending them to the scan API when they match the namespaces filter.

Comment (imilchev) [reply motor/discovery/k8s/resolver_namespace.go:42]: I also ran a few tests and it seems to be working as expected. Waiting on @joelddiaz to triple-check 😄

**Review by czunker — APPROVED** [review]
