### PR TITLE
🐛 Add upstream config to run command

### LINKED ISSUE #956: `run` command is missing the upstream config
**Describe the bug**
When executing `cnquery run` with queries that require an upstream config, this config isn't present. But running the same query with `cnquery shell` works.

**To Reproduce**

1. Run `cnquery run local -c 'platform.eol'`
2. Note the error `failed to create resource 'platform.eol': mondoo upstream configuration is missing`

**Expected behavior**
`cnquery` should connect upstream and the query should succeed.

**Screenshots or CLI Output**
```
cnquery run local -c 'platform.eol' 
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
Query encountered errors:
failed to create resource 'platform.eol': mondoo upstream configuration is missing
platform.eol: no data available
```

In contrast to:
```
cnquery shell local 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
  ___ _ __   __ _ _   _  ___ _ __ _   _ 
 / __| '_ \ / _` | | | |/ _ \ '__| | | |
| (__| | | | (_| | |_| |  __/ |  | |_| |
 \___|_| |_|\__, |\__,_|\___|_|   \__, |
  mondoo™      |_|                |___/  interactive shell

cnquery> platform.eol
platform.eol: platform.eol date=2027-04-01 00:00:00 +0000 UTC

```

### PR DESCRIPTION
**Pull request by czunker**
This also adds the upstream config to all commands executed as plugin.

Fixes #956

### CODE REVIEW

**Comment by czunker** [comment]
@arlimus / @chris-rock It works, but I'm not sure this is the correct place to integrate with https://github.com/mondoohq/cnquery/pull/71 as intended.

File: apps/cnquery/cmd/plugin.go [hunk 1]
```diff
@@ -109,6 +121,20 @@ func (c *cnqueryPlugin) RunQuery(conf *proto.RunQueryConfig, out shared.OutputHe
 		out.WriteString("[")
 	}
 
+	var upstreamConfig *resources.UpstreamConfig
+	serviceAccount := opts.GetServiceCredential()
+	if serviceAccount != nil {
+		certAuth, _ := upstream.NewServiceAccountRangerPlugin(serviceAccount)
```
Comment (joelddiaz) [inline apps/cnquery/cmd/plugin.go]: Is it really not possible for this to error because of the ReadConfig() above, or should this potential error case be handled?

**Review by joelddiaz — COMMENTED** [review]
Looks good. Just a question about the potential for an error codepath.

File: apps/cnquery/cmd/plugin.go (hunk 1 above)
Comment (czunker) [reply apps/cnquery/cmd/plugin.go]: Nice catch. Thanks.

That was a problem in multiple commands. I added a check.

**Review by joelddiaz — APPROVED** [review]
