### PR TITLE
🐛 fix tls.certificates is not properly initialized

### LINKED ISSUE #2441: tls.certificates is not properly initialized
**Describe the bug**

```
±> cnquery shell host mondoo.com
→ connected to Network API
  ___ _ __   __ _ _   _  ___ _ __ _   _ 
 / __| '_ \ / _` | | | |/ _ \ '__| | | |
| (__| | | | (_| | |_| |  __/ |  | |_| |
 \___|_| |_|\__, |\__,_|\___|_|   \__, |
  mondoo™      |_|                |___/  interactive shell

cnquery> tls.certificates
tls.certificates: null
cnquery> 
±> cnquery shell host mondoo.com
→ connected to Network API
  ___ _ __   __ _ _   _  ___ _ __ _   _ 
 / __| '_ \ / _` | | | |/ _ \ '__| | | |
| (__| | | | (_| | |_| |  __/ |  | |_| |
 \___|_| |_|\__, |\__,_|\___|_|   \__, |
  mondoo™      |_|                |___/  interactive shell

cnquery> tls.ciphers
tls.ciphers: [
  0: "TLS_AES_256_GCM_SHA384"
  1: "TLS_CHACHA20_POLY1305_SHA256"
  2: "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
  3: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
  4: "TLS_AES_128_GCM_SHA256"
  5: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
]
cnquery> tls.certificates
tls.certificates: [
  0: certificate serial="12:c8:88:71:0b:33:e3:d6:0a:0f:fa:b1:61:a6:4f:c6" subject.commonName="mondoo.com" subject.dn="CN=mondoo.com"
  1: certificate serial="02:00:8e:b2:02:33:36:65:8b:64:cd:db:9b" subject.commonName="GTS CA 1D4" subject.dn="CN=GTS CA 1D4,O=Google Trust Services LLC,C=US"
  2: certificate serial="77:bd:0d:6c:db:36:f9:1a:ea:21:0f:c4:f0:58:d3:0d" subject.commonName="GTS Root R1" subject.dn="CN=GTS Root R1,O=Google Trust Services LLC,C=US"
]
cnquery> 
```

- calling `tls.certificates` returns null
- calling `tls.ciphers` and then `tls.certificates` returns the correct values

**To Reproduce**

see above

**Expected behavior**

`tls.certificates` is always populates

### PR DESCRIPTION
**Pull request by mariuskimmina**
Fixes #2441

### CODE REVIEW

File: providers/network/resources/tls.go [hunk 1]
```diff
@@ -318,14 +318,20 @@ func (s *mqlTls) certificates(params interface{}) ([]interface{}, error) {
 	// We leverage the fact that params has to be created first, and that params
 	// causes this field to be set. If it isn't, then we cannot determine it.
 	// (TODO: use the recording data to do this async)
-	s.Certificates.State = plugin.StateIsSet | plugin.StateIsNull
-	return nil, nil
+	if len(s.Certificates.Data) <= 0 {
```
Comment (chris-rock) [inline providers/network/resources/tls.go]: Is there ever a case where len is < 0?

Comment (mariuskimmina) [reply providers/network/resources/tls.go]: if the site doesn't have a certificate, meaning it's http only, I guess

Edit: missread the question, yea less then 0 should never happen

Comment (mariuskimmina) [reply providers/network/resources/tls.go]: But I now tested this again and it seem to still be somewhat flaky even with this change :thinking:

Comment (mariuskimmina) [reply providers/network/resources/tls.go]: Ah, no, the flakyness was because I changed to this branch but I forgot to edit the providers.yaml, it does seem to be reliable.

**Review by chris-rock — APPROVED** [review]
Works like a charm, thank you @mariuskimmina
