### PR TITLE
🐛 Continue scanning when connect to one asset fails

### LINKED ISSUE #2080: scan exits on first error while scanning multiple assets
**Describe the bug**
When I scan a k8s cluster with multiple images, the scan exits on the first error:
```
cnquery-9b15 scan k8s --discover container-images --config ~/workspace/mondoo/sa-edge-default.json --verbose 
! CLI pre-processing encountered an issue error="unknown flag: --config"
DBG using provider k8s with connector k8s
DBG Started a new runtime (1 total)
...
→ discover related assets for 1 asset(s)
DBG Started a new runtime (2 total)
DBG resolved 16 assets
DBG running provider plugin path=/home/christian/.config/mondoo/providers/os/os
FTL failed to run scan error="rpc error: code = Unknown desc = GET https://ghcr.io/v2/mondoohq/mondoo-operator/manifests/sha256-34e4bc26bf44ae1dddab394f5e9449664d6fe3a4.sig: MANIFEST_UNKNOWN: manifest unknown"
```

I ran the scan against a minikube, with a custom operator image only present in the minikube cluster, not in the registry it is tagged with.

**To Reproduce**

1. Use latest v9 release
2. Run above command
3. Note the error

**Expected behavior**
I'd expect cnquery to scan the other images, as it does with v8.

**Desktop (please complete the following information):**

- cnquery v9 beta15

### PR DESCRIPTION
**Pull request by czunker**
Fixes #2080

### CODE REVIEW

**Comment by czunker** [comment]
With cnspec, this now looks like this:
```
cnspec scan k8s --discover container-images --config ~/workspace/mondoo/sa-edge-default.json                                                                                                                                                          
→ loaded configuration from /home/christian/workspace/mondoo/sa-edge-default.json using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
x unable to connect to asset error="rpc error: code = Unknown desc = GET https://ghcr.io/v2/mondoohq/mondoo-operator/manifests/sha256-34e4bc26bf44ae1dddab394f5e9449664d6fe3a4.sig: MANIFEST_UNKNOWN: manifest unknown"
→ synchronize assets

 quay.io/jetstack/cert-manager-controller@2642e7f41545      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% score
 quay.io/jetstack/cert-manager-webhook@a3205d026246      
...
```

File: providers/assets.go [hunk 1]
```diff
@@ -59,7 +59,7 @@ func detectAssets(runtime *Runtime, assetCandidates []*inventory.Asset, upstream
 			Upstream: upstreamConfig,
 		})
 		if err != nil {
-			return err
```
Comment (imilchev) [inline providers/assets.go:62]: shall we at least log the error?

Comment (czunker) [reply providers/assets.go:62]: I had this in a previous version, but then it showed up twice here:
```
→ discover related assets for 1 asset(s)
x failed to connect to asset error="rpc error: code = Unknown desc = GET https://ghcr.io/v2/mondoohq/mondoo-operator/manifests/sha256-34e4bc26bf44ae1dddab394f5e9449664d6fe3a4.sig: MANIFEST_UNKNOWN: manifest unknown" asset=
x unable to connect to asset error="rpc error: code = Unknown desc = GET https://ghcr.io/v2/mondoohq/mondoo-operator/manifests/sha256-34e4bc26bf44ae1dddab394f5e9449664d6fe3a4.sig: MANIFEST_UNKNOWN: manifest unknown"
→ synchronize assets

```

So, I removed the logging.

**Review by imilchev — APPROVED** [review]
