### PR TITLE
🧹 Cleanup workaround for GCP shutdown

### LINKED ISSUE #1823: 🧹 remove gcp-snapshot cleanup workaround
**Describe the bug**
I think, this can now be removed: https://github.com/mondoohq/cnquery/blob/ebe8c80f79d1faf596b52668f860f6bae7d4f590/apps/cnquery/cmd/plugin.go#L105

This also happens here: https://github.com/mondoohq/cnquery/blob/main/providers/gcp/provider/provider.go#L184

**To Reproduce**

1. Remove the workaround
2. Run a gcp snapshot scan on a GCP VM
3. Check that the scan works and the mount & disk is cleaned up afterwards

**Expected behavior**
The cleanup should happen without the workaround.

### PR DESCRIPTION
**Pull request by czunker**
Fixes #1823

### CODE REVIEW

**Comment by czunker** [comment]
This only works, when https://github.com/mondoohq/cnquery/issues/2126 is solved.

**Comment by czunker** [comment]
> This only works, when #2126 is solved.

According to https://github.com/mondoohq/cnquery/pull/2187#issuecomment-1769986452, this should no longer be needed.

File: apps/cnquery/cmd/plugin.go [hunk 1]
```diff
@@ -122,14 +122,6 @@ func (c *cnqueryPlugin) RunQuery(conf *run.RunQueryConfig, runtime *providers.Ru
 		out.WriteString("[")
 	}
 
-	// FIXME: workaround for gcp-snapshot
-	// For a gcp-snapshot asset, we start with a GCP connection.
-	// This get's overridden by a filesystem connection. The filesystem connection is what we need for the scan
-	// But later, we need the GCP runtime to cleanup the snapshot disk
-	if runtime.Provider.Instance.Name == "gcp" && runtime.Provider.Connection.Name == "filesystem" {
```
Comment (chris-rock) [inline apps/cnquery/cmd/plugin.go:129]: we can clean this because it happens here https://github.com/mondoohq/cnquery/blob/main/providers/gcp/provider/provider.go#L184 now

**Review by chris-rock — APPROVED** [review]
Thank you @czunker
