### PR TITLE
🐛 Fix retrieval of report usage by going back a week.

### LINKED ISSUE #2073: Google Workspace Reports Return Error
**Describe the bug**

Accessing reports returns a 400 from Google:

```
cnspec> googleworkspace.roles
googleworkspace.roles: [
  0: googleworkspace.role name="_SERVICE_ADMIN_ROLE"
  1: googleworkspace.role name="_GROUPS_ADMIN_ROLE"
...
cnspec> googleworkspace.report.users
googleapi: Error 400: Data for dates later than 2023-10-01 is not yet available. Please check back later, invalid
googleworkspace.report.users.list: null
```

**To Reproduce**

Setup the Google Workspace integration and run a scan with the default policies (all queries use googleworkspace.report.users) or access the report from the shell as above.

Replicated on both v8.28.4 and v9 beta14.

### PR DESCRIPTION
**Pull request by preslavgerchev**
Fixes #2073 

Try and retrieve the report usage for each day, going back a week. If data is present, we return that.
Minor code cleanup by using the time.DateOnly format, available since go 1.20

### CODE REVIEW

**Comment by czunker** [comment]
I can give this a try, once my test account is working again.

**Comment by czunker** [comment]
Got it working and do now longer see the error message:
```
GOOGLE_APPLICATION_CREDENTIALS=~/workspace/mondoo/xyz.json cnquery run google-workspace --customer-id 123 --impersonated-user-email me@example.com -c "googleworkspace.report.users"
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
googleworkspace.report.users.list: [
  1: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc1/2023-10-08
  2: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc2/2023-10-08
  0: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc3/2023-10-08
  3: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc4/2023-10-08
  4: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc5/2023-10-08
  5: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc6/2023-10-08
  6: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc7/2023-10-08
  7: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc8/2023-10-08
  8: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc9/2023-10-08
  9: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc10/2023-10-08
  10: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc11/2023-10-08
  11: googleworkspace.report.usage id = googleworkspace.report.usage/123/abc12/2023-10-08
]
```

File: providers/google-workspace/resources/reports.go [hunk 1]
```diff
@@ -125,46 +123,69 @@ func (g *mqlGoogleworkspaceReportUsers) list() ([]interface{}, error) {
...
+
+	if len(usageReports) == 0 {
+		// try and fetch usage for each of the past 7 days
+		attempts := 7
+		for attempts > 0 {
 			date = date.Add(-24 * time.Hour)
-			// try fetching from a day before
-			usageReports, err = reportsService.UserUsageReport.Get("all", date.Format(ISO8601)).CustomerId(conn.CustomerID()).Do()
-			if err != nil {
+			reports, err := fetchReportUsage(g.MqlRuntime, reportsService, conn.CustomerID(), date.Format(time.DateOnly))
```
Comment (czunker) [inline providers/google-workspace/resources/reports.go:139]: Learned something new today: `time.DateOnly` Thanks.

**Review by czunker — APPROVED** [review]
Thanks @preslavgerchev
