### PR TITLE
🐛 Fix file stat when run with sudo

### LINKED ISSUE #512: Core Resource: File, --sudo yields no user or groupnames
**Describe the bug**
Using the `--sudo` switch when using `cnquery` leads to unusable output.
`cnquery shell local --sudo`

**To Reproduce**

` cnquery> file($filename).group`

` cnquery> file($filename).name`

See error below:
image

**Expected behavior**
The same as above without the `--sudo` switch:
`cnquery shell local`
image

**Desktop (please complete the following information):**
Tested on:
- Debian 11
- Ubuntu 22.04 
using:
- cnquery 7.5.0 (0d6924f0, 2022-11-22T12:33:11Z)
- cnquery v7.3.0 (7594c926, unknown)

### PR DESCRIPTION
**Pull request by czunker**
Fixes #512

Signed-off-by: Christian Zunker <christian@mondoo.com>

### CODE REVIEW

File: motor/providers/local/local_unix.go [hunk 1]
```diff
@@ -6,11 +6,19 @@ package local
...
 	"os"
 	"syscall"
+
+	pos "go.mondoo.com/cnquery/motor/providers/os"
 )
 
 func (p *Provider) fileowner(stat os.FileInfo) (int64, int64) {
 	uid := int64(-1)
 	gid := int64(-1)
+	if p.Sudo != nil {
```
Comment (jaym) [inline motor/providers/local/local_unix.go]: do we need to check for sudo? Are there other cases where we might have this `pos.FileInfo` type?

**Review by jaym — APPROVED** [review]

File: motor/providers/local/local_unix.go (hunk 1 above)
Comment (czunker) [reply motor/providers/local/local_unix.go]: You are correct, this also works without the sudo check. Removed it.
