### PR TITLE
🧹 Test provided cert/pass when creating an ms365 connection.

### LINKED ISSUE #1113: Validate provided pem files to ensure they include private key
**Describe the bug**
If a user provides us with a .pem file that does not include the private key we don't throw an error in the application. Instead there's an error in each check in the policies, but those are not immediately apparent on the CLI. 

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**
Validate the .PEM file is the correct format and throw an error if it's missing either the certificate or the private key portion.

**Screenshots or CLI Output**
```
cnquery scan ms365 --tenant-id 2919c383-55f1-4d5b-9d3e-12345 --certificate-path ~/dev/cert.pem
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1

 Microsoft 365 tenant 2919c383-55f1-4d5b-9d3e-12345 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% score: X


Asset: Microsoft 365 tenant 2919c383-55f1-4d5b-9d3e-12345
----------------------------------------------------------------

Data queries:
mondoo.jobEnvironment: {
  id: "client.mondoo.com"
  name: "Mondoo Client"
}
platform.release: ""
platform.title: "Microsoft 365"
mondoo.version: "8.3.0"
platform.arch: ""

Controls:
! Error: Ensure that mobile device encryption is enabled to prevent unauthorized access to mobile data
! Error: Ensure that mobile devices require complex passwords (Type = Alphanumeric)
! Error: Ensure that at least three global admins are designated and not more than four
! Error: Ensure modern authentication for SharePoint applications is required
! Error: Ensure mailbox auditing for all users is Enabled
! Error: Ensure that mobile devices require complex passwords (Simple Passwords = Blocked)
! Error: Ensure devices lock after a period of inactivity to prevent unauthorized access
! Error: Ensure mail transport rules do not whitelist specific domains
! Error: Ensure that Office 365 passwords never Expire
! Error: Ensure modern authentication for Exchange Online is enabled
! Error: Ensure self-service password reset is enabled
! Error: Ensure notifications for internal users sending malware is Enabled
! Error: Ensure that the security Defaults is disabled
! Error: Enable Azure AD Identity Protection sign-in
! Error: Ensure Microsoft 365 audit log search is Enabled
! Error: Ensure that no third party integrated applications are allowed
! Error: Ensure that DKIM is enabled for all Exchange Online Domains
! Error: Ensure the Common Attachment Types Filter is enabled
! Error: Ensure that the legacy authentication has been disabled by Conditional access policies
! Error: Ensure that minimum password length has been set in order to prevent any brute force attack
! Error: Ensure all forms of mail forwarding are blocked and/or disabled
. Skipped: Ensure that 'Users can create Azure AD Tenants' is set to 'No'
! Error: Ensure Sender Policy Record (SPF) exists for each domain in Exchange
! Error: Ensure mobile devices require the use of a password
! Error: Ensure that multi-factor authentication has been enabled for all users
! Error: Ensure multifactor authentication is enabled for all users in administrative roles
! Error: Enable Azure AD Identity Protection sign-in
! Error: Ensure expiration time for external sharing links is set
! Error: Ensure that mobile devices require a minimum password length to prevent brute force attacks
! Error: Ensure Exchange Online Spam Policies are set to notify administrators


Scanned 1 assets

Microsoft 365
    X Microsoft 365 tenant 2919c383-55f1-4d5b-9d3e-12345

For detailed output, run this scan with "-o full".

See more scan results and asset relationships on the Mondoo Console: NOPE
```

### PR DESCRIPTION
**Pull request by preslavgerchev**
Fixes #1113 

image

```
~/go/bin/cnquery shell ms365 --certificate-path ~/cert-no-pk.pem --client-id xxxxxxx --tenant-id xxxxxxxx
→ loaded configuration from /Users/preslavgerchev/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=0
x could not connect to asset error="could not parse provided certificate at /Users/preslavgerchev/azure-cert.pem: found no private key" asset=
FTL could not resolve assets
```

### CODE REVIEW

**Comment by misterpantz** [comment]
Hi! Could we provide some help on resolving this? I was thinking we could send them to this topic in the docs? 
https://mondoo.com/docs/platform/saas/ms365/

File: motor/providers/microsoft/auth.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ func (p *Provider) GetTokenCredential() (azcore.TokenCredential, error) {
 		case vault.CredentialType_pkcs12:
 			certs, privateKey, err := azidentity.ParseCertificates(p.cred.Secret, []byte(p.cred.Password))
 			if err != nil {
-				return nil, errors.Wrap(err, "could not parse certificate")
+				return nil, errors.Wrap(err, "could not parse provided certificate")
```
Comment (czunker) [inline motor/providers/microsoft/auth.go]: Do we know the path of the certificate at this point? This might be helpful to the user.

Comment (preslavgerchev) [reply motor/providers/microsoft/auth.go]: good point, we know this (via the param that is passed in) but this will take a more wiring to get it done.

i will look into it

**Comment by tas50** [comment]
> Hi! Could we provide some help on resolving this? I was thinking we could send them to this topic in the docs? https://mondoo.com/docs/platform/saas/ms365/

We'd want cnspec/CLI docs to send them too for this one.

File: motor/providers/microsoft/auth.go (hunk 1 above)
Comment (preslavgerchev) [reply motor/providers/microsoft/auth.go]: done, ive updated the PR description with the new error message that also shows the cert path
