### PR TITLE
🐛 Fix panic on attempts to use ref as a map value

### LINKED ISSUE #6217: Panic on MQL query
**Describe the bug**
Panic on executing a valid? MQL query.

**To Reproduce**

1. Open cnquery shell on a linux host in version
2. Execute `file('/etc/oratab').content.lines.where(_ != /^#/).where(_.length != 0).map(_.split(":")[1]).map(path: path + "/bin/oraversion").map(path: {"p": file(path).user.name })`
3. Observe panic

**Screenshots or CLI Output**

Image

Complete Stacktrace: 

```shell
cnquery> file('/etc/oratab').content.lines.where(_ != /^#/).where(_.length != 0).map(_.split(":")[1]).map(path: path + "/bin/oraversion").map(path: {"p": file(path).user.name }→ reported panic to Mondoo Platform
panic: Failed to read bytes into integer: ''
	 [recovered]
	panic: panic compiling "file('/etc/oratab').content.lines.where(_ != /^#/).where(_.length != 0).map(_.split(\":\")[1]).map(path: path + \"/bin/oraversion\").map(path: {\"p\": file(path).user.name })": Failed to read bytes into integer: ''
	 [recovered, repanicked]

goroutine 1 [running]:
go.mondoo.com/cnquery/v12/providers-sdk/v1/upstream/health.ReportPanic({0x1beda36, 0x7}, {0x1ea2038, 0x7}, {0x1ea2058, 0xc}, {0x0, 0x0, 0x0?})
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/upstream/health/errors.go:36 +0x198
panic({0x18c8900?, 0xc000733260?})
	/home/runner/_work/_tool/go/1.25.1/x64/src/runtime/panic.go:783 +0x132
go.mondoo.com/cnquery/v12/mqlc.Compile.func1()
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:2235 +0xb3
panic({0x182e2c0?, 0xc000733240?})
	/home/runner/_work/_tool/go/1.25.1/x64/src/runtime/panic.go:783 +0x132
go.mondoo.com/cnquery/v12/llx.bytes2int({0x0, 0x0, 0x0})
	/home/runner/_work/cnquery/cnquery/llx/byte_conversions.go:35 +0x19f
go.mondoo.com/cnquery/v12/llx.(*Primitive).dereferenceTypeV2(0xc000265030, {0xc0005bdddc, 0x1}, 0xc000a89a40)
	/home/runner/_work/cnquery/cnquery/llx/types.go:142 +0x19a
go.mondoo.com/cnquery/v12/llx.(*Primitive).dereferenceTypeV2(0xc000265030, {0xc0005bddda, 0x3}, 0xc000a89a40)
	/home/runner/_work/cnquery/cnquery/llx/types.go:150 +0xee
go.mondoo.com/cnquery/v12/llx.(*Chunk).DereferencedTypeV2(0xc0005bde00?, 0xc0005bde02?)
	/home/runner/_work/cnquery/cnquery/llx/types.go:42 +0xa7
go.mondoo.com/cnquery/v12/llx.(*CodeV2).DereferencedBlockType(0x600000000?, 0xc000a267e0?)
	/home/runner/_work/cnquery/cnquery/llx/code.go:151 +0x45
go.mondoo.com/cnquery/v12/mqlc.compileArrayMap(0xc00025d380, {0xc0005bdc28?, 0xc000225640?}, 0xc000a26850?, {0xc0005bd694, 0x3}, 0x1a8c400?)
	/home/runner/_work/cnquery/cnquery/mqlc/builtin_array.go:484 +0x1ac
go.mondoo.com/cnquery/v12/mqlc.(*compiler).compileBuiltinFunction(0xc000225300?, 0x2?, {0xc0005bd694?, 0x3?}, 0xc000a26948?, 0x41c5ca?)
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:847 +0xa5
go.mondoo.com/cnquery/v12/mqlc.(*compiler).compileBoundIdentifierWithMqlCtx(0xc00025d380, {0xc0005bd694, 0x3}, 0xc000a26b98, 0xc000225300)
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:1013 +0x8b6
go.mondoo.com/cnquery/v12/mqlc.(*compiler).compileBoundIdentifier(...)
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:925
go.mondoo.com/cnquery/v12/mqlc.(*compiler).compileOperand(0xc00025d380, 0xc00083b680)
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:1463 +0x46b
go.mondoo.com/cnquery/v12/mqlc.(*compiler).compileExpression(...)
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:1539
go.mondoo.com/cnquery/v12/mqlc.(*compiler).compileAndAddExpression(0xc00025d380, 0x2d16440?)
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:1543 +0x2b
go.mondoo.com/cnquery/v12/mqlc.(*compiler).compileExpressions(0xc00025d380, {0xc000080dd0, 0x1, 0x500000041cf94?})
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:1619 +0x2ff
go.mondoo.com/cnquery/v12/mqlc.(*compiler).CompileParsed(0xc00025d380, 0x1ea2038?)
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:2092 +0x35
go.mondoo.com/cnquery/v12/mqlc.CompileAST(0xc000aa61e0, {0x0?, 0x0?}, {{0x1ec66e0, 0xc000529090}, 0x0, {0x1ec9128, 0x2d45800}, {0xc00075af40, 0x4, ...}})
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:2182 +0x428
go.mondoo.com/cnquery/v12/mqlc.compile({0xc000862210?, 0x4?}, {0x0, 0x0}, {{0x1ec66e0, 0xc000529090}, 0x0, {0x1ec9128, 0x2d45800}, {0xc00075af40, ...}})
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:2206 +0x125
go.mondoo.com/cnquery/v12/mqlc.Compile({0xc000862210?, 0xc000a27190?}, {0x0?, 0x0?}, {{0x1ec66e0, 0xc000529090}, 0x0, {0x1ec9128, 0x2d45800}, {0xc00075af40, ...}})
	/home/runner/_work/cnquery/cnquery/mqlc/mqlc.go:2239 +0xbc
go.mondoo.com/cnquery/v12/cli/shell.(*Completer).CompletePrompt(0xc0004a2380, {{0xc0008620b0, 0xa8}, 0xa8, 0x56})
	/home/runner/_work/cnquery/cnquery/cli/shell/completer.go:50 +0x1d1
github.com/c-bata/go-prompt.(*CompletionManager).Update(...)
	/home/runner/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/completion.go:68
github.com/c-bata/go-prompt.(*Prompt).Run(0xc00077a480)
	/home/runner/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/prompt.go:99 +0x65c
go.mondoo.com/cnquery/v12/cli/shell.(*Shell).RunInteractive(0xc000a3a3c0, {0x0, 0x0})
	/home/runner/_work/cnquery/cnquery/cli/shell/shell.go:174 +0x7c5
go.mondoo.com/cnquery/v12/apps/cnquery/cmd.StartShell(0xc0001b3800, 0xc000b0e120)
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cmd/shell.go:174 +0x7b5
go.mondoo.com/cnquery/v12/apps/cnquery/cmd.init.func31(0xc000529040?, 0xc0001b3800, 0xc000547380?)
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cmd/shell.go:50 +0x28
go.mondoo.com/cnquery/v12/cli/providers.setConnector.func2(0x2cfd920, {0x2d45800, 0x0, 0x0})
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:582 +0xb96
github.com/spf13/cobra.(*Command).execute(0x2cfd920, {0x2d45800, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1019 +0xae7
github.com/spf13/cobra.(*Command).ExecuteC(0x2cfcda0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1148 +0x465
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.1/command.go:1071
go.mondoo.com/cnquery/v12/apps/cnquery/cmd.Execute()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cmd/root.go:86 +0x7d
main.main()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cnquery.go:16 +0x8c
```

**Desktop (please complete the following information):**

- OS: Oracle Linux 
- OS Version: 9.7
- Cnquery Version: cnquery 12.11.0 (0dd66e4799c5, 2025-11-25T12:33:25Z)

### PR DESCRIPTION
**Pull request by slntopp**
Fixes #6217

This fix consists of two parts:
1. Fixes compile-time map type handling (panic) by enforcing `Any` types for `Ref`s
2. Fixes further dereferencing issue by implementing converter for `MapLike`

### CODE REVIEW

File: llx/data_conversions.go [hunk 1]
```diff
@@ -814,6 +814,21 @@ func (b *blockExecutor) resolveValue(arg *Primitive, ref uint64) (*RawData, uint
 			res[i] = c.Value
 		}
 
+		// type is in arg.Value
+		return &RawData{
+			Type:  typ,
+			Value: res,
+		}, 0, nil
+	case types.MapLike:
```
Comment (preslavgerchev) [inline llx/data_conversions.go:822]: super nice @slntopp , can we add some tests around this?
