### PR TITLE
🐛 Use configured api-proxy

### LINKED ISSUE #2277: cnquery/ cnspec not working behind proxy
I have used the terraform deployment (https://github.com/mondoohq/samples/pull/46) to test cnspec behind a forward proxy.

The asset synchronization is not working

```bash
cnspec scan local --config /etc/opt/mondoo/mondoo.yml
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets
FTL failed to run scan error="failed to do request: Post \"https://us.api.mondoo.com/PolicyResolver/SynchronizeAssets\": dial tcp 34.160.242.34:443: i/o timeout"
```

The health check is also not working

```bash
cnspec --config /etc/mondoo/mondoo.yml serve --timer 1
→ loaded configuration from /etc/mondoo/mondoo.yml using source --config
→ start cnspec client=//agents.api.mondoo.app/spaces/awesome-shannon-882559/agents/2Wu3Mn0GD5KXRUi1QAutHZPmij7 service_account=//agents.api.mondoo.app/spaces/awesome-shannon-882559/serviceaccounts/2Wu3MhBS7rG9TdMlkJfYVHvLwpZ space=//captain.api.mondoo.app/spaces/awesome-shannon-882559 version=9.2.1
→ using service account credentials
→ configure inventory to scan local operating system
→ could not perform health check error="failed to do request: Post \"https://us.api.mondoo.com/Health/Check\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

### PR DESCRIPTION
**Pull request by czunker**
Fixes #2277

### CODE REVIEW

**Comment by czunker** [comment]
So far, I tested:
- `cnquery status` with parameter and config file
- `cnquery run --api-proxy http://127.0.0.1:3128 -c "asset.vulnerabilityReport"`
- `cnquery scan --api-proxy http://127.0.0.1:3128`

In a locally running squid, I see the connects to the API:
```
1697778604.808    426 172.17.0.1 TCP_TUNNEL/200 5251 CONNECT us.api.mondoo.com:443 - HIER_DIRECT/34.160.242.34 -
```

I need to test cnspec and the setup reported in the issue.

**Comment by czunker** [comment]
cnquery `asset.eol` now also works:
```
cnquery run --config sa-edge-default.json -c "asset.eol"
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from sa-edge-default.json using source --config
asset.eol: asset.eol date=2028-06-10 00:00:00 +0000 UTC
```

File: providers/os/resources/asset_eol.go [hunk 1]
```diff
@@ -67,7 +67,17 @@ func initAssetEol(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[st
 	// get new advisory report
 	// start scanner client
 
-	scannerClient, err := newAdvisoryScannerHttpClient(mcc.ApiEndpoint, mcc.Plugins, mcc.HttpClient)
```
Comment (czunker) [inline providers/os/resources/asset_eol.go]: This didn't work as expected before:
```
admin@ip-10-0-101-143:~$ ./cnquery version
cnquery 8.28.4 (f7739318, 2023-09-20T10:09:07Z)
admin@ip-10-0-101-143:~$ ./cnquery run --config sa-edge-default.json -c "platform.eol"
→ no provider specified, defaulting to local.
  Use --help for a list of available providers.
→ loaded configuration from sa-edge-default.json using source --config
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
Query encountered errors:
failed to create resource 'platform.eol': failed to do request: Post "https://api.edge.mondoo.com/AdvisoryScanner/IsEol": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
platform.eol: no data available
```

It would bypass the proxy and fetch data from upstream. The actual HTTP client was working, but it ignored the proxy.

File: providers/arista/go.sum [hunk 2]
```diff
@@ -249,8 +249,6 @@ github.com/yuin/goldmark v1.1.25/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9de
 github.com/yuin/goldmark v1.1.27/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9decYSb74=
 github.com/yuin/goldmark v1.1.32/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9decYSb74=
 github.com/yuin/goldmark v1.2.1/go.mod h1:3hX8gzYuyVAZsxl0MRgGTJEmQBFcNTphYh9decYSb74=
-go.mondoo.com/ranger-rpc v0.5.1 h1:OaVQntDJWDRgbc9nXBP4wOCR9h9Bij8LgHHs86IguGk=
-go.mondoo.com/ranger-rpc v0.5.1/go.mod h1:3YKcqFrlPgaB4FZ4EoLgdmRtwMQdO7RoAkZYFn+F1eY=
```
Comment (arlimus) [inline providers/arista/go.sum]: It looks like all of these files are unrelated to the change at hand, let's separate them.

File: providers-sdk/v1/upstream/upstream.go [hunk 3]
```diff
@@ -60,8 +61,19 @@ func (c *UpstreamConfig) InitClient() (*UpstreamClient, error) {
...
+func (c *UpstreamConfig) httpClient() *http.Client {
+	if c.ApiProxy == "" {
+		return ranger.DefaultHttpClient()
+	}
+	proxy, err := url.Parse(c.ApiProxy)
+	if err != nil {
+		log.Fatal().Err(err).Msg("could not parse proxy URL")
+	}
+	return ranger.NewHttpClient(ranger.WithProxy(proxy))
+}
```
Comment (arlimus) [inline providers-sdk/v1/upstream/upstream.go:79]: This looks good!

**Review by arlimus — CHANGES_REQUESTED** [review]

File: providers/os/resources/asset_eol.go (hunk 1 above)
Comment (arlimus) [reply providers/os/resources/asset_eol.go]: Thank you for verifying!

Comment (arlimus) [reply providers/os/resources/asset_eol.go]: I ran a test myself with a local proxy, because this looked like it should have worked with the initial version. I got it working and verified on the proxy as well:

```
CONNECT   Oct 20 23:57:35.271 [1928765]: Connect (file descriptor 4): 127.0.0.1
CONNECT   Oct 20 23:57:35.271 [1928765]: Request (file descriptor 4): CONNECT us.api.mondoo.com:443 HTTP/1.1
INFO      Oct 20 23:57:35.271 [1928765]: No upstream proxy for us.api.mondoo.com
INFO      Oct 20 23:57:35.271 [1928765]: opensock: opening connection to us.api.mondoo.com:443
INFO      Oct 20 23:57:35.293 [1928765]: opensock: getaddrinfo returned for us.api.mondoo.com:443
CONNECT   Oct 20 23:57:35.346 [1928765]: Established connection to host "us.api.mondoo.com" using file descriptor 5.
INFO      Oct 20 23:57:35.346 [1928765]: Not sending client headers to remote machine
INFO      Oct 20 23:57:35.583 [1928765]: Closed connection between local client (fd:4) and remote client (fd:5)
```

```bash
> cnquery run docker image 216c552ea5ba --config ~/.config/mondoo/mondoo.yml -c "asset.eol"
! using builtin provider for os
! using builtin provider for os
→ loaded configuration from /home/zero/.config/mondoo/mondoo.yml using source --config
asset.eol: asset.eol date=2027-03-31 17:00:00 -0700 PDT
```

That you for checking tho, i suspect it may have been missing the provider update before? I used the builtin os provider to make sure it used this very code-path.

```go
	scannerClient, err := newAdvisoryScannerHttpClient(mcc.ApiEndpoint, mcc.Plugins, mcc.HttpClient)
```

File: providers/os/resources/platform_advisories.go [hunk 4]
```diff
@@ -59,9 +59,19 @@ func fetchVulnReport(runtime *plugin.Runtime) (interface{}, error) {
...
+		upstreamClient, err = mcc.UpstreamConfig.InitClient()
+		if err != nil {
+			return nil, err
+		}
+	}
+
 	// get new advisory report
 	// start scanner client
-	scannerClient, err := newAdvisoryScannerHttpClient(mcc.ApiEndpoint, mcc.Plugins, mcc.HttpClient)
+	scannerClient, err := newAdvisoryScannerHttpClient(mcc.ApiEndpoint, mcc.Plugins, upstreamClient.HttpClient)
```
Comment (arlimus) [inline providers/os/resources/platform_advisories.go]: Also confirmed this with the above example :) Thank you for being diligent and checking tho. It was probably the builtin provider, but I'll ask Patrick to verify too.

**Review by arlimus — APPROVED** [review]

**Comment by arlimus** [comment]
Thank you for fixing these. I pushed it over the finish line by removing the go.mod changes, which didn't relate to this PRs work, and reverting the additional proxy calls, since they were likely caused by the dev environment. Nice approach overall!

**Comment by arlimus** [comment]
Note: this change requires a forced re-release of all providers, since they otherwise ignore the proto change ;)
