### PR TITLE
🐛 Only delete volumes we created

### LINKED ISSUE #500: cnspec deletes available EBS volume after failed scan
**Describe the bug**
EBS Volume is deleted after failed scan:
```
./cnspec scan aws ec2 ebs volume vol-04b6ac8dc3bff9fd3
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
! resolver does not support discovery target 'auto', the following are supported:  resolver="AWS EC2 EBS Resolver"
→ resolved assets resolved-assets=1
→ syncing assets
→ connecting to asset vol-04b6ac8dc3bff9fd3
! WARNING: you are using an early access feature feature=AWS_EC2_EBS status=experimental
→ validate exists volume={"AccountId":"***","Id":"vol-04b6ac8dc3bff9fd3","PlatformId":"//platformid.api.mondoo.app/runtime/aws/ec2/v1/accounts/***/regions/us-east-1/volumes/vol-04b6ac8dc3bff9fd3","Region":"us-east-1"}
→ attach volume volume id=vol-04b6ac8dc3bff9fd3
x attach volume err error="operation error EC2: AttachVolume, https response error StatusCode: 400, RequestID: e362c3a3-1856-426f-b293-e2aa6b72d21e, api error InvalidVolume.ZoneMismatch: The volume 'vol-04b6ac8dc3bff9fd3' is not in the same availability zone as instance 'i-0b24443c8d18fdbab'" volume=vol-04b6ac8dc3bff9fd3
x unable to complete setup step error="operation error EC2: AttachVolume, https response error StatusCode: 400, RequestID: e362c3a3-1856-426f-b293-e2aa6b72d21e, api error InvalidVolume.ZoneMismatch: The volume 'vol-04b6ac8dc3bff9fd3' is not in the same availability zone as instance 'i-0b24443c8d18fdbab'"
→ unmount volume
x failed to unmount dir error="no such file or directory"
x failed to unmount dir error="no such file or directory"
x unable to unmount volume error="no such file or directory"
→ detach volume
x unable to detach volume error="operation error EC2: DetachVolume, https response error StatusCode: 400, RequestID: 069a6932-dba4-46fd-9d6b-8375a0b960aa, api error IncorrectState: Volume 'vol-04b6ac8dc3bff9fd3' is in the 'available' state."
→ delete created volume
→ remove created dir
```

**To Reproduce**
1. Create EBS volume
2. Get EBS volume ID
3. Scan EBS volume from EC2 instance with above command
4. See delete message at the end of the output
5. Check EBS volumes

**Expected behavior**
We shouldn't delete the volume.

**Screenshots or CLI Output**
-

**Desktop (please complete the following information):**
- cnspec 7.4.0

**Additional context**
Came across this while trying to reproduce mondoohq/cnspec#198

### PR DESCRIPTION
**Pull request by czunker**
In some cases, e.g., snapshot scans we create volumes which we have to delete afterwards. But when scanning an available volume, we shouldn't delete it afterwards.

Fixes #500

Signed-off-by: Christian Zunker <christian@mondoo.com>

### CODE REVIEW

**Comment by czunker** [comment]
This is where it happens:
https://github.com/mondoohq/cnquery/blob/main/motor/providers/awsec2ebs/setup.go#L66

We need this structure to unmount the filesystem later on. We could also add another field instead of the bool, holding the original volume ID and a possible new volume ID.

File: motor/providers/awsec2ebs/provider.go [hunk 1]
```diff
@@ -192,9 +193,12 @@ func (p *Provider) Close() {
 	if err != nil {
 		log.Error().Err(err).Msg("unable to detach volume")
 	}
-	err = p.DeleteCreatedVolume(ctx, p.tmpInfo.scanVolumeId)
-	if err != nil {
-		log.Error().Err(err).Msg("unable to delete volume")
+	// only delete the volume if we created it, e.g., if we're scanning a snapshot
+	if p.tmpInfo.createdExtraVolume {
```
Comment (chris-rock) [inline motor/providers/awsec2ebs/provider.go]: Could we use tags for that? eg. we annotate the volume / snapshot that we created and only delete it if it has our tag. Advantage would be that we can recover from states where the execution was interrupted.

Comment (czunker) [reply motor/providers/awsec2ebs/provider.go]: From what I understand, the API does not support an additional filter for tags on the delete call: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteVolume.html

But perhaps @preslavgerchev or @vjeffrey know how this could work.

Comment (preslavgerchev) [reply motor/providers/awsec2ebs/provider.go]: Pushed up a commit to get tags and delete based on them. A quick test shows it works so far, feel free to adjust!

File: motor/providers/awsec2ebs/provider.go [hunk 2]
```diff
@@ -199,6 +199,8 @@ func (p *Provider) Close() {
 				log.Error().Err(err).Msg("unable to delete volume")
 			}
 		}
+	} else {
```
Comment (chris-rock) [inline motor/providers/awsec2ebs/provider.go:203]: Since the default behaviour is now that we do not delete the volume, I would add an info log, once the volume was deleted.

File: motor/providers/awsec2ebs/types.go [hunk 3]
```diff
@@ -53,16 +53,18 @@ type SnapshotId struct {
...
+	Tags        map[string]string
 }
 
 func resourceTags(resourceType types.ResourceType, instanceId string) []types.TagSpecification {
 	return []types.TagSpecification{
-		{ResourceType: resourceType,
+		{
+			ResourceType: resourceType,
 			Tags: []types.Tag{
 				{Key: aws.String("Created By"), Value: aws.String("Mondoo")},
```
Comment (chris-rock) [inline motor/providers/awsec2ebs/types.go:70]: Should we stick to the standard AWS tag "createdBy" https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/aws-tags.html?

**Review by chris-rock — CHANGES_REQUESTED** [review]
I love the new tag bases approach, makes it much more reliable and predictable. I added a few nit picks, once that is in, LGTM

File: motor/providers/awsec2ebs/types.go (hunk 3 above)
Comment (czunker) [reply motor/providers/awsec2ebs/types.go:70]: Changed.

File: motor/providers/awsec2ebs/provider.go (hunk 2 above)
Comment (czunker) [reply motor/providers/awsec2ebs/provider.go:203]: Done.

**Comment by czunker** [comment]
Thanks for your help @preslavgerchev

**Review by preslavgerchev — APPROVED** [review]

File: motor/providers/awsec2ebs/types.go [hunk 4]
```diff
@@ -53,18 +53,20 @@ type SnapshotId struct {
...
 }
 
 func resourceTags(resourceType types.ResourceType, instanceId string) []types.TagSpecification {
 	return []types.TagSpecification{
-		{ResourceType: resourceType,
+		{
+			ResourceType: resourceType,
 			Tags: []types.Tag{
-				{Key: aws.String("Created By"), Value: aws.String("Mondoo")},
+				{Key: aws.String("createdBy"), Value: aws.String("Mondoo")},
```
Comment (vjeffrey) [inline motor/providers/awsec2ebs/types.go:69]: is there a reason this was changed from "Created By" to "createdBy" ? i believe we have other logic that depends on this tag naming in the lambda

Comment (czunker) [reply motor/providers/awsec2ebs/types.go:69]: Was requested here: https://github.com/mondoohq/cnquery/pull/504#discussion_r1031076186

Because of compliance with the standard AWS tags.

Where can we find out whether we need this specific form of the tag?

Comment (vjeffrey) [reply motor/providers/awsec2ebs/types.go:69]: https://gitlab.com/mondoolabs/mondoo/-/blob/master/apps/mondoo-lambda/cloudformation/mondoo-lambda-cf.json#L490 we currently depend on the tag being "Created By": "Mondoo"

Comment (vjeffrey) [reply motor/providers/awsec2ebs/types.go:69]: can we add both tags for now, and then we'll transition the lambda to the new one? i'll make a ticket for the followup

Comment (czunker) [reply motor/providers/awsec2ebs/types.go:69]: Sure. Added it.

**Review by vjeffrey — APPROVED** [review]

**Review by chris-rock — APPROVED** [review]
Thank you @czunker
