### PR TITLE
🐛 Fix vagrant asset information

### LINKED ISSUE #1761: v9 vagrant asset is missing a name
**Describe the bug**
Testing with https://github.com/mondoohq/cnquery/pull/1740 also an asset scanned via vagrant should get a name, because vagrant uses ssh underneath.

But:
```
cnquery run vagrant default -c "asset{ name }"                                                                                                                        
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
asset: {
  name: ""
}
```
vs.
```
cnquery run ssh -i /home/christian/workspace/mondoo/examples/.vagrant/machines/default/virtualbox/private_key vagrant@127.0.0.1:2222 -c "asset.name" 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
asset.name: "ubuntu-jammy"

```

**To Reproduce**

1. Start a vagrant VM
2. Connect via vagrant like above
3. Note the error

**Expected behavior**
Both connections should show the same asset name.

### PR DESCRIPTION
**Pull request by czunker**
Fixes #1761

### CODE REVIEW

File: providers-sdk/v1/util/configure/configure.go [hunk 1]
```diff
@@ -170,6 +171,15 @@ func rewireDependencies(providers []string) {
 	deps := ""
 	replace := ""
 	for _, provider := range providers {
+		_, err := os.Stat("providers/" + provider + "/go.mod")
```
Comment (czunker) [inline providers-sdk/v1/util/configure/configure.go:174]: The os provider has no `go.mod` file. This broke before this fix:
```make providers/config 
go run ./providers-sdk/v1/util/configure/configure.go -f providers.yaml -o providers/builtin_dev.go
→ (1/3) configured builtin providers path=providers/builtin_dev.go providers=["os"]
DBG build provider 1/1 provider=os
→ (2/3) built providers providers=["os"]
DBG go mod tidy
FTL failed to go mod tidy error="exit status 1"
exit status 1
make: *** [Makefile:150: providers/config] Error 1
```

**Comment by czunker** [comment]
This is now closer to what we have in v8:
```
cnquery run vagrant default -c "asset{ name title platform kind runtime ids }"                                                                                                             
! using builtin provider for os
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
! using builtin provider for os
asset: {
  kind: "virtualmachine"
  title: "Ubuntu 22.04.1 LTS, Virtual Machine"
  platform: "ubuntu"
  runtime: ""
  ids: [
    0: "//platformid.api.mondoo.app/hostname/ubuntu-jammy"
  ]
  name: "default"
}
```

**Review by vjeffrey — APPROVED** [review]
