### PR TITLE
🧹 Do not fetch trails if they are not part of the account.

### LINKED ISSUE #1184: aws.cloudtrail.trails - Query encountered errors: * job err: : failed to create resource 'aws.kms.key': kms key does not exist
**Describe the bug**
```
cnspec> mondoo
mondoo: mondoo version="8.7.0"
```

```
cnspec> aws.cloudtrail {*}
Query encountered errors:
1 error occurred:
        * job err: : failed to create resource 'aws.kms.key': kms key does not exist
aws.cloudtrail: {
  trails: job err: : failed to create resource 'aws.kms.key': kms key does not exist
}
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

### PR DESCRIPTION
**Pull request by preslavgerchev**
Fixes #1184 

We cannot query information about a trail (log group, kms key,  etc) if that trail is coming from another account. In that case, we should just skip it

### CODE REVIEW

File: resources/packs/aws/aws_cloudtrail.go [hunk 1]
```diff
@@ -119,9 +121,14 @@ func (t *mqlAwsCloudtrail) getTrails(provider *aws_provider.Provider) []*jobpool
 				if regionVal != core.ToString(trail.HomeRegion) {
 					continue
 				}
-
+				// we skip trails that are not coming from the account that is being scanned
+				// such trails are organization trails, created from another (master) acc in the org
+				trailArn := core.ToString(trail.TrailARN)
+				if !strings.Contains(trailArn, acc) {
```
Comment (vjeffrey) [inline resources/packs/aws/aws_cloudtrail.go]: is there any information we can gather about organization trails?  we should be able to work around not being able to fetch a kms key or log group, since keys can be deleted anytime, it's always a problem we can run into

Comment (preslavgerchev) [reply resources/packs/aws/aws_cloudtrail.go]: yeah, we can also just not err out if the key or the log group are not found.

re the org trails: there's a bool on the trail that indicates what it is. i am not sure if we can use it since i'd assume we want to show that trail in the master acc it has been created from
